name: Containers

# NOTE(mhayden): Restricting branches prevents jobs from being doubled since
# a push to a pull request triggers two events.
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master
  schedule:
    # Build containers on weekdays at 6AM UTC.
    - cron: "0 6 * * 1,2,3,4,5"

jobs:
  buildah:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Build buildah container
        run: docker build -f builds/buildah -t quay.io/osbuild/buildah:latest .

      - name: Push the container
        run: |
          docker login -u="osbuild+github_actions" -p="${{ secrets.QUAY_TOKEN }}" quay.io
          docker push quay.io/osbuild/buildah:latest

  build:
    runs-on: ubuntu-latest
    # needs:
    #   - buildah
    container:
      image: quay.io/osbuild/buildah:latest
      options: "--privileged"
    strategy:
      fail-fast: false
      matrix:
        containers:
          - name: ansible
            file: ansible
    env:
      # Ensure buildah generates manifests that Docker can read.
      BUILDAH_FORMAT: docker
      # Running buildah inside docker requires vfs instead of overlayfs.
      STORAGE_DRIVER: vfs
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Build the container with buildah
        run: |
          buildah bud --squash -f builds/${{ matrix.containers.file }} \
            -t quay.io/osbuild/${{ matrix.containers.name }} .

      - name: Push the container
        run: |
          buildah login -u="osbuild+github_actions" \
            -p="${{ secrets.QUAY_TOKEN }}" quay.io
          buildah push quay.io/osbuild/${{ matrix.containers.name }}
