name: Containers

# NOTE(mhayden): Restricting branches prevents jobs from being doubled since
# a push to a pull request triggers two events.
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master
  schedule:
    # Build containers on weekdays at 6AM UTC.
    - cron: "0 6 * * 1,2,3,4,5"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers:
          - name: ansible
            file: ansible
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

     - name: Build Fedora 31 container
        run: |
          docker build -f builds/${{ matrix.containers.file }} \
            -t quay.io/osbuild/${{ matrix.containers.name }}:latest .

      - name: Push the container
        run: |
          docker login -u="osbuild+github_actions" -p="${{ secrets.QUAY_TOKEN }}" quay.io
          docker push quay.io/osbuild/${{ matrix.containers.name }}:latest
